# Site settings
baseurl = "https://nemocdz.github.io/My-blog/"
# HTML Language Code Reference, such as en, zh-cn
languageCode = "zh-cn"
title = "Nemocdz's Blog"
theme = "hugo-theme-cactus-plus"
# Enter your tracking code to enable Google Analytics
#googleAnalytics = "your_google_analytics_code"
hasCJKLanguage = true
publishDir = "docs"

[params]
	name = "Nemocdz"
	description = "Blog Description"
	bio = "iOS Dev & Photographer"
	enableRSS = true
	paginate = 6

	# Disqus comment
	disqusShortname = "your_disqus_short_name"
	# Disable disqus comments by set `enableDisqus = "false"`
	enableDisqus = false

	# Duoshuo comment
	duoshuoShortname = "your_duoshuo_short_name"
	# Disable duoshuo comments by set `enableDuoshuo = "false"`
	enableDuoshuo = false

	enableGithubIssuesTips = false

	# Enable googleAnalytics
	enableGoogleAnalytics = false

	# Enable baiduAnalytics
	enableBaiduAnalytics = false
	# Baidu Tongji Code
	baiduAnalytics = 'your_baidu_tongji_code'

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = "RSS"
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "我是谁？皮卡丘"
	tweet = ""
	share = ""
	# 404 page
	title404 = "我的博客挂了"
	subtitle404 = "请告诉我QAQ，QQ757765420"

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
  	# The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  	socialIconStyle = "circle"


# Add additional social link entries underneath
[social]
	facebook = "https://www.facebook.com/nemocdz"
  	twitter = "https://twitter.com/Nemocdz"
  	github = "https://github.com/Nemocdz"